### ISSUE TITLE
Support of HiDPI

### ISSUE THREAD

**Issue by KaraRyougi** [TricksterGuy/complx#103]
Minor UI bugs when used in HiDPI:

- Scroll bar is too tiny.

- Column titles cannot be fully displayed.

See [https://imgur.com/a/dpddd](url) for screenshot.

**Comment by ausbin** [comment]
still wayyyyy better than it was in previous releases tbh

**Comment by TricksterGuy** [comment]
This is not a problem I can fix.  The underlying GUI toolkit library I am using has issues.  This is apparently fixed in the current release of that GUI library, however a package has not trickled down to Ubuntu yet

**Comment by TricksterGuy** [comment]
Well what do you know a new development release of [wxWidgets](https://www.wxwidgets.org/news/2018/02/wxwidgets-3.1.1-released/) was released today.  However since the version number is odd it is not an thing that should be used for actual stuff.

It may be worth compiling the program against that version.
