### ISSUE TITLE
Console stuck

### ISSUE THREAD

**Issue by KPPhiri** [TricksterGuy/complx#109]
Console stuck in top left corner, and cannot move it to read outputs
<img width="1207" alt="screen shot 2018-03-03 at 10 51 46 am" src="https://user-images.githubusercontent.com/35545437/36936279-447f2b3c-1ed1-11e8-9e89-63e8f604f652.png">

**Comment by skyman** [comment]
Since this is a Mac issue and the Mac version is not officially supported by Brandon, it's kind of on me, the Mac version guy, to fix these issues, so here we go.

Your best bet here is to close complx, increase your screen resolution (or making everything smaller, these are all in System Preferences -> Displays) and then relaunching it.

There are some good ways of moving windows by using the resize features. For example, on the main complx window, you can move it by putting your mouse on the right side edge which reveals the horizontal resize cursor, then click and hold the mouse still for a second, then finally move the mouse vertically and it will move instead of resizing.

However, because the console window in this case is not resizable, the cursor icon does not appear and you cannot move the window in this manner. Perhaps @TricksterGuy could update that for a later version but right now your best bet is changing your resolution to get it off of there.

**Comment by TricksterGuy** [comment]
Move the complx window down and load a file?
